
@baseURL = http://localhost:4000

###
// POST - Verifica email e senha
POST {{baseURL}}/login
Content-Type: application/json

# {
#     "email": "camila@gmail.com",
#     "senha": "camila01"
# }

{
    "email": "ateste02@gmail.com",
    "senha": "ateste02"
}