//Teste de requisições - Registro
//Instalar o plugin REST Client no VS code, para utilizar este recurso.

@baseURL = http://localhost:4000
@id = 60ec19b203f2990004e1fbac

###
// GET - Lista os registros
GET {{baseURL}}/registros
Content-Type: application/json

###
// GET - Lista um registro pelo id
GET {{baseURL}}/registros/{{id}}
Content-Type: application/json

###
// POST - Inclui um novo registro
POST {{baseURL}}/registros
Content-Type: application/json

{   
    "nome": "Ateste 03",
    "status": "ativo",
    "cpf": "89655555555",
    "email": "ateste03@gmail.com",
    "senha": "ateste03"
}

###
// DELETE - Apaga um registro pelo id
DELETE  {{baseURL}}/registros/{{id}}
Content-Type: application/json

###
// PUT - Alterar registro
PUT {{baseURL}}/registros
Content-Type: application/json

{
    "_id": "60ecab8f6d46340cd0dc3775",
    "nome": "Ateste 03 alterado",
    "status": "ativo",
    "cpf": "89655555555",
    "email": "ateste03@gmail.com",
    "senha": "ateste03"
}