//Teste de requisições - Registro
//Instalar o plugin REST Client no VS code, para utilizar este recurso.

@baseURL = http://localhost:4000
@id = 60e4be3bcbb50c7428b72c62

###
// GET - Lista os registros
GET {{baseURL}}/registros
Content-Type: application/json

###
// GET - Lista um registro pelo id
GET {{baseURL}}/registros/{{id}}
Content-Type: application/json

###
// POST - Inclui um novo registro
POST {{baseURL}}/registros
Content-Type: application/json

{   
    "nome": "TesteImg",
    "status": "inativo",
    "cpf": "8965235487955",
    "email": "testeimg@gmail.com",
    "senha": "testeimg",
    "nivel": 999,
}

###
// DELETE - Apaga um registro pelo id
DELETE  {{baseURL}}/registros/{{id}}
Content-Type: application/json

###
// PUT - Alterar registro
PUT {{baseURL}}/registros
Content-Type: application/json

{   
    "_id": "60ecdd130057d41314985a7e",
    "nome": "TesteImg",
    "status": "ativo",
    "cpf": "8965235487955",
    "email": "testeimg@gmail.com",
    "senha": "testeimg",
    "nivel": 999,
}
